[theme]
base = "dark"

# Colours
textColor = "#FAFAFA"
primaryColor = "#00BFFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
borderColor = "#444444"

# Widgets
showWidgetBorder = true

# Base text
font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "https://fonts.googleapis.com/css2?family=Inter:wght@600&display=swap"
headingFontWeights = [600, 600, 600, 200, 600, 200]
headingFontSizes = ["3rem", "1.5rem", "1rem", "1rem", "0.8rem", "0.8rem"]
